---
- name: OWNCLOUD | add database for owncloud
  mysql_db:
    name: "{{ owncloud_db_table.name_to_be_created }}"
    collation: "{{ owncloud_db_table.collation | default('utf8_general_ci') }}"
    encoding: "{{ owncloud_db_table.encoding | default('utf8') }}"
    state: present

- name: OWNCLOUD | create mysql user for owncloud
  mysql_user:
    name: "{{ owncloud_db_user }}"
    host: "{{ owncloud_db_host }}"
    password: "{{ owncloud_db_pass }}"
    priv: "{{ owncloud_db_table.name_to_be_created }}.*:ALL"
    state: present